name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
  push:
    branches:    
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:    
      - main
  schedule:
    - cron: 15 6 * * 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ls
 Test:
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - run: echo Testing...

  Load-Test:
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - run: |
          echo Testing...
          sleep 15

  Production:
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    needs:
      - Test
      - Load-Test
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo Step x deploying...
          sleep 10
      - run: |
          echo Step x deploying...
          sleep 10
      - run: |
          echo Step x deploying...
          sleep 10
      - run: |
          echo Step x deploying...
          sleep 10
      - run: |
          echo Step x deploying...
          sleep 10